In [1]:
import pandas as pd

In [2]:
category_translation=pd.read_csv(r"C:\Users\ss\Desktop\E-Commerce Business Intelligence & Customer Analytics\Dataset\product_category_name_translation.csv")

In [3]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [4]:
category_translation.shape

(71, 2)

In [5]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [6]:
category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [8]:
category_translation.describe().T

                              count unique            top freq
product_category_name            71     71   beleza_saude    1
product_category_name_english    71     71  health_beauty    1

In [9]:
category_translation.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [10]:
category_translation.duplicated().sum()

np.int64(0)

In [11]:
category_translation["product_category_name"].nunique()

71

In [12]:
category_translation["product_category_name_english"].nunique()

71

In [13]:
category_translation["product_category_name"].value_counts()

product_category_name
beleza_saude                        1
alimentos                           1
fashion_esporte                     1
fashion_underwear_e_moda_praia      1
construcao_ferramentas_seguranca    1
                                   ..
malas_acessorios                    1
cool_stuff                          1
fashion_calcados                    1
audio                               1
seguros_e_servicos                  1
Name: count, Length: 71, dtype: int64

In [1]:
 # Category translation table contains complete and unique category mappings,
# so no additional cleaning is required.